workflows:
  nexus-build:
    name: NEXUS Overlay
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Build APK
        script: |
          flutter clean
          flutter pub get
          flutter build apk --release \
            --target-platform android-arm64 \
            --android-skip-build-dependency-validation
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      
